services:
  postgresql:
    image: postgres:16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_DB: clicker-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql: { }